select distinct a.nr_atendimento
from PRESCR_MEDICA a, atendimento_paciente b
where a.nr_atendimento = b.nr_atendimento
and b.CD_ESTABELECIMENTO = 1
and a.CD_PRESCRITOR = 148
AND a.DT_LIBERACAO BETWEEN '01/01/2018' AND '05/07/2018';


SELECT count(a.NR_ATENDIMENTO)--, DT_EVOLUCAO 
FROM EVOLUCAO_PACIENTE a, ATENDIMENTO_PACIENTE b
WHERE a.NR_ATENDIMENTO = b.NR_ATENDIMENTO
and b.CD_ESTABELECIMENTO = 1
and a.CD_MEDICO = 1136760 --
AND a.DT_LIBERACAO IS NOT NULL
AND a.DT_LIBERACAO BETWEEN '01/01/2018' AND '05/07/2018' ;
