SELECT us.DS_USUARIO, a.VL_PARAMETRO
FROM
	FUNCAO_PARAM_USUARIO a,
	USUARIO us
WHERE
	a.NM_USUARIO_PARAM = us.NM_USUARIO
	--AND a.NR_SEQUENCIA = 54
	--AND a.CD_FUNCAO = 24
	AND a.NR_SEQUENCIA =:nr_param
	AND a.CD_FUNCAO =:funcao
	AND us.CD_ESTABELECIMENTO = 1
ORDER BY
	us.DS_USUARIO
