select IE_RESPONSAVEL
from PROCESSO_APROV_RESP
where CD_CARGO = 266;

/*COLOCA USUÁRIO DA ROSI NO LUGAR DO FURINI*/
update PROCESSO_APROV_RESP set IE_RESPONSAVEL = 'F', NM_USUARIO_REGRA  = 'RPB', cd_cargo = null
where cd_cargo = 266;

/*COLOCA USUARIO DO FURINI DE VOLTA*/
update PROCESSO_APROV_RESP set IE_RESPONSAVEL = 'C', NM_USUARIO_REGRA = null, cd_cargo = 266
where NM_USUARIO_REGRA  = 'RPB';

commit;