SELECT distinct c.DS_FUNCAO,
  a.DS_TITULO,
  a.CD_RELATORIO,
  b.IE_EXIGE_PERFIL
FROM RELATORIO_FUNCAO b, RELATORIO_PERFIL d, PERFIL e,
  RELATORIO a,
  funcao c
WHERE a.NR_SEQUENCIA = b.NR_SEQ_RELATORIO
AND b.CD_FUNCAO      = c.CD_FUNCAO
and a.NR_SEQUENCIA = d.NR_SEQ_RELATORIO
and d.CD_PERFIL= e.CD_PERFIL
and e.CD_ESTABELECIMENTO = 1
AND b.cd_funcao     IN (915, 713, 917)
ORDER BY c.DS_FUNCAO, a.ds_titulo;


