SELECT c.DS_FUNCAO,
  a.DS_TITULO,
  a.CD_RELATORIO
FROM RELATORIO_FUNCAO b,
  RELATORIO a,
  funcao c
WHERE a.NR_SEQUENCIA = b.NR_SEQ_RELATORIO
AND b.CD_FUNCAO      = c.CD_FUNCAO
AND b.cd_funcao     IN (915, 713, 917)
ORDER BY c.DS_FUNCAO